### ISSUE TITLE
baselines MPI Parallelization

### ISSUE THREAD

**Issue by vlad17** [mwhittaker/deeprl_project#22]
I just realized that the baselines MPI stuff is if you have multiple GPUs, not for multiple instances.

So we really don't want to [log every instance](https://github.com/mwhittaker/deeprl_project/blob/master/src/run_atari_ppo.py#L30) as we do here, it should really only log if rank == 0 and other wise the log should be disabled, as we had before.

My mistake.

**Comment by mwhittaker** [comment]
Merged into #30
